### ISSUE TITLE
Narrow text field in mobile page view

### ISSUE THREAD

**Issue by pil-in-a** [danielroehrig/diary#38] opened 2022-05-29 14:00 UTC
Hello,

the app is quite simple, so I don't think it needs mobile app. But the mobile page view should be fixed.
Text field displays narrow (only three words per line or so), when I open the app in Android browser (tried Fennec, Chrome, Opera).
Rest of GUI scales nice.
![Screenshot_20220529-103716](https://user-images.githubusercontent.com/95473349/170872894-c71e691d-a509-4e5a-b450-026ff1fb1b35.png)
![Screenshot_20220529-103726](https://user-images.githubusercontent.com/95473349/170872896-6b3218f4-ce6f-4046-afd3-d67559632f03.png)

**Comment by danielroehrig** [comment] 2022-05-29 14:39
you're right. That looks horrible.

**Comment by danielroehrig** [comment] 2022-05-29 15:03
Great. I cannot reproduce that in the "normal" browser, but I see it when I use the firefox on mobile so.... this is gonna be fun.

**Comment by danielroehrig** [comment] 2022-05-29 15:28
I've slapped some CSS !important on what I guess is the right class and it looks fine now. Will be in the next release.

**Comment by danielroehrig** [comment] 2022-06-06 14:07
Should be fixed now in Version 0.0.7. Could you please check?

**Comment by pil-in-a** [comment] 2022-06-07 09:34
It is looking great. Thanks!
![screenshot](https://pilinas.mywire.org:32681/s/FZNaNcHWMd8kWNs/preview)

**Closed** 2022-06-08 07:33 UTC
Labels: bug
